### PR TITLE
Contributions to RuntimeMeshBuilder

### PR DESCRIPTION
**Pull request by RumbleballTheReal**
-Improved some function parameters
-Added functions for array merging (vertices, colors and indices)
--omitted normal/tangent/uv for now as they are much more specific.

### CODE REVIEW

**Comment by RumbleballTheReal** [comment]
Sorry. We have the code in perforce, I don't want two source controls access the same files.
Missed that when copying in the additions.
First time with git/githun as well. 
Thanks for the report, Its added to the file.

**Comment by MaximeDup** [comment]
Hey, awesome! Thanks for the fast update ! :D

**Comment by Loriborn** [comment]
Hello there, I'm having trouble building the plugin for 4.20.1 out-of-the-box.

**Comment by RumbleballTheReal** [comment]
> Hello there, I'm having trouble building the plugin for 4.20.1 out-of-the-box.
Only when including this pullrequest or even if you exclude it? 
What does the compiler complain about?

I'm on UE4.19.

**Comment by Loriborn** [comment]
Ah seems to be an RMC issue not specific to the pull request

**Pull request merged**
