### PR TITLE
[4.19] Fixes for clang warnings and ARM platforms

### PR DESCRIPTION
**Pull request by NuclearCookie**

### CODE REVIEW

**Comment by AngusPei** [comment]
Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Commands.cpp ->505 line
FD3D11ShaderResourceView* SRV = ResourceCast(SRVRHI);

SRV is null
Using UnrealEngine-4.19.0-release

**Comment by NuclearCookie** [comment]
Your comment is unrelated to this PR. If you want help, make your own issue and give more information.

**Comment by Koderz** [comment]
@NuclearCookie  Completely forgot about this PR. This should be fixed in the current version, if not please feel free to submit a new one!

**Comment by NuclearCookie** [comment]
@Koderz Clang warnings are fixed but not ARM compilation.
Take a look at the code in Source/RuntimeMeshComponent/Private/RuntimeMeshSection.cpp in this PR. ( check the diff )

**Comment by Koderz** [comment]
Ah, you mean the extra template arguments?  I'll add those tonight!

**Comment by NuclearCookie** [comment]
Yes, that's it! 
Thanks for the work on this component!

**Comment by Koderz** [comment]
@NuclearCookie  I made those changes, let me know if there are any others!  Thanks for the PR!

**Pull request closed without merging**
